### ISSUE TITLE
Container names don't match between template and shell script

### ISSUE THREAD

**Issue by mozillamonks** [nyxkrage/mastodon-docker#1]
Hey there, thanks for putting this together!

I notice that your template is following a naming convention of mastodon_web, mastodon_db, etc; but the shell script is expecting mastodonWeb, mastondonDb, etc. This mismatch now causes script failure.

**Comment by nyxkrage** [comment]
Hey, I am aware, I just haven't gotten around to pushing up the new templates, the container names where changed to camelCase due to minio not working with underscores in the hostname.
This should be fixed later today.
